# E-mail Spam Detection with Multinomial Naive-Bayes and Gaussian Naive-Bayes

### Description: This project is about email spam detection. In this projects was used dataset which was downloaded from Kaggle. In this dataset, words has already converted to the numbers. So, I just used here Multinomial Naive-Bayes Model and Gaussian Naive-Bayes Model.
### Also, I used this project Confusion Matrix and Shuffle Split methods for evaluation of models.

## 1. Import Libraries

In [42]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.naive_bayes import MultinomialNB, GaussianNB
from sklearn.model_selection import train_test_split, ShuffleSplit, cross_val_score
from sklearn.metrics import confusion_matrix

## 2. Import Dataset

In [4]:
df = pd.read_csv('emails.csv')
df.head()

Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  jay  \
0   Email 1    0   0    1    0    0   0    2    0    0  ...         0    0   
1   Email 2    8  13   24    6    6   2  102    1   27  ...         0    0   
2   Email 3    0   0    1    0    0   0    8    0    0  ...         0    0   
3   Email 4    0   5   22    0    5   1   51    2   10  ...         0    0   
4   Email 5    7   6   17    1    5   2   57    0    9  ...         0    0   

   valued  lay  infrastructure  military  allowing  ff  dry  Prediction  
0       0    0               0         0         0   0    0           0  
1       0    0               0         0         0   1    0           0  
2       0    0               0         0         0   0    0           0  
3       0    0               0         0         0   0    0           0  
4       0    0               0         0         0   1    0           0  

[5 rows x 3002 columns]

## 3. Clean the dataset

In [10]:
df.drop(columns='Email No.', inplace=True)
df.head()

the  to  ect  and  for  of    a  you  hou  in  ...  connevey  jay  valued  \
0    0   0    1    0    0   0    2    0    0   0  ...         0    0       0   
1    8  13   24    6    6   2  102    1   27  18  ...         0    0       0   
2    0   0    1    0    0   0    8    0    0   4  ...         0    0       0   
3    0   5   22    0    5   1   51    2   10   1  ...         0    0       0   
4    7   6   17    1    5   2   57    0    9   3  ...         0    0       0   

   lay  infrastructure  military  allowing  ff  dry  Prediction  
0    0               0         0         0   0    0           0  
1    0               0         0         0   1    0           0  
2    0               0         0         0   0    0           0  
3    0               0         0         0   0    0           0  
4    0               0         0         0   1    0           0  

[5 rows x 3001 columns]

## 4. Split the data

In [39]:
target = ['Prediction']
X = df.drop(columns=target)
y= df[target]

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [26]:
X_train.head()

the  to  ect  and  for  of    a  you  hou  in  ...  enhancements  \
3164    6   4    2    1    2   8   39    5    2   5  ...             0   
2067    0   0    1    0    1   0    3    0    0   0  ...             0   
4717   40  28    4   21   12  12  260   24    4  78  ...             0   
2505    5   1    1    0    1   1   12    0    0   3  ...             0   
2268    6   6    3    1    1   0   64    0    1   7  ...             0   

      connevey  jay  valued  lay  infrastructure  military  allowing  ff  dry  
3164         0    0       0    0               0         0         0   1    0  
2067         0    0       0    0               0         0         0   0    0  
4717         0    0       0    0               0         0         0   3    0  
2505         0    0       0    0               0         0         0   0    0  
2268         0    0       0    1               0         0         0   1    0  

[5 rows x 3000 columns]

## 5. Build Multinomial Naive-Bayes Model

In [27]:
model = MultinomialNB()
model.fit(X_train, y_train)

C:\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MultinomialNB()

## 6. Predict the y_test

In [33]:
y_pred = model.predict(X_test)

## 7. Evaluate the model with Shuffle Split

In [43]:
cv = ShuffleSplit(n_splits=5, test_size=0.3, random_state=0)
cross_val_score(model, X, y, cv=cv)

C:\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y,

array([0.94136598, 0.94523196, 0.9375    , 0.95167526, 0.94652062])

## 8. Evaluate the model with Confusion Matrix

In [44]:
cm = confusion_matrix(y_test,y_pred)
cm

array([[704,  35],
       [ 12, 284]], dtype=int64)

## 9. Calculate the model score

In [45]:
model.score(X_test, y_test)

0.9545893719806763

## 10.Build the Gaussian Naive-Bayes Model

In [31]:
model1= GaussianNB()

## 11. Train the model and predict the y_test

In [37]:
model1.fit(X_train,y_train)
y_pred1 = model1.predict(X_test)

C:\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [38]:
cm = confusion_matrix(y_test, y_pred1)
cm

array([[697,  42],
       [ 12, 284]], dtype=int64)